# touch: 0
name: 'Create Dummy Commits'

on:
  push:
    branches: [ 'main' ]
    paths-includes:
      - '.github/workflows/create_commits.yaml'
  pull_request:
    types: [ 'closed' ]
    branches: [ 'main' ]
    paths-includes:
      - '.github/workflows/create_commits.yaml'

jobs:
  CreateCommitsAndTags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create commits and tags
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          for i in $(seq -f "%03g" 1 103);
          do
            now=$(date)
            echo "dummy commit ${i}: ${now}" > touch.txt
            git add touch.txt

            git commit -m "dummy commit ${i}: ${now}"
            git push origin main -f

            git tag -a "dummy_tag_${i}" -m "dummy tag ${i}"
            git push origin "dummy_tag_${i}"            
          done
