# touch: 0
name: 'Create Dummy Releases'

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/create_releases.yaml'
  pull_request:
    types: [ 'closed' ]
    branches: [ 'main' ]
    paths:
      - '.github/workflows/create_releases.yaml'

env:
  VERSION: 'v2'

jobs:
  CreateReleases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create releases
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          for i in $(seq -f "%03g" 1 103);
          do
            now=$(date -u +%Y%m%d-%s)
            year=$(date -u +%Y)
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/btnguyen2k/long-repo/releases \
              -d "{\"tag_name\": \"${{ env.VERSION }}.${year}.${i}\", \"name\": \"my_release_${{ env.VERSION }}.${year}.${i}_${now}\", \"body\": \"dummy release ${{ env.VERSION }}.${year}.${i}-${now}\"}"
          done
