# touch: 0
name: 'Create Dummy Branches'

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/create_branches.yaml'
  pull_request:
    types: [ 'closed' ]
    branches: [ 'main' ]
    paths:
      - '.github/workflows/create_branches.yaml'

jobs:
  CreateBranches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Branches
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          for i in $(seq -f "%03g" 1 103);
          do
            git checkout -b dummy_branch_${i}
            git push origin dummy_branch_${i} -f
          done
